# Generated by Codex on 2026-04-29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("system", "System"),
                            ("worker", "Worker"),
                            ("telegram", "Telegram"),
                            ("admin", "Admin"),
                        ],
                        default="user",
                        max_length=32,
                    ),
                ),
                ("action", models.CharField(max_length=128)),
                ("entity_type", models.CharField(max_length=128)),
                ("entity_id", models.CharField(blank=True, max_length=128)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="cars.car",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit event",
                "verbose_name_plural": "audit events",
                "db_table": "audit_events",
            },
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["actor", "occurred_at"], name="audit_actor_time_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["action", "occurred_at"], name="audit_action_time_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["entity_type", "entity_id"], name="audit_entity_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["car", "occurred_at"], name="audit_car_time_idx"),
        ),
    ]
