# Generated by Codex on 2026-04-29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("email", "Email"),
                            ("in_app", "In app"),
                            ("system", "System"),
                        ],
                        default="telegram",
                        max_length=32,
                    ),
                ),
                ("recipient", models.CharField(blank=True, max_length=255)),
                ("event_type", models.CharField(max_length=128)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("due_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("dedup_key", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_events",
                        to="cars.car",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification event",
                "verbose_name_plural": "notification events",
                "db_table": "notification_events",
            },
        ),
        migrations.CreateModel(
            name="ReminderEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("time_based", "Time based"),
                            ("odometer", "Odometer"),
                            ("maintenance", "Maintenance"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("odometer_due", models.PositiveBigIntegerField(blank=True, null=True)),
                ("source_object_type", models.CharField(blank=True, max_length=128)),
                ("source_object_id", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("triggered", "Triggered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=32,
                    ),
                ),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_events",
                        to="cars.car",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminder_events",
                        to="notifications.notificationevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminder_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "reminder event",
                "verbose_name_plural": "reminder events",
                "db_table": "reminder_events",
            },
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(fields=["status", "due_at"], name="notif_status_due_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(fields=["user", "status"], name="notif_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(fields=["car", "due_at"], name="notif_car_due_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(fields=["event_type"], name="notif_event_type_idx"),
        ),
        migrations.AddIndex(
            model_name="reminderevent",
            index=models.Index(fields=["status", "due_at"], name="remind_status_due_idx"),
        ),
        migrations.AddIndex(
            model_name="reminderevent",
            index=models.Index(fields=["car", "status"], name="remind_car_status_idx"),
        ),
        migrations.AddIndex(
            model_name="reminderevent",
            index=models.Index(fields=["user", "status"], name="remind_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="reminderevent",
            index=models.Index(fields=["source_object_type", "source_object_id"], name="remind_source_idx"),
        ),
    ]
