# Generated by Django 5.2.13 on 2026-04-14 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("plate_number", models.CharField(max_length=32)),
                ("normalized_plate_number", models.CharField(max_length=32, unique=True)),
                ("brand", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=64)),
                ("year", models.PositiveSmallIntegerField()),
                ("vin", models.CharField(blank=True, max_length=32, null=True, unique=True)),
                (
                    "powertrain_type",
                    models.CharField(
                        choices=[("ice", "ICE"), ("hybrid", "Hybrid"), ("ev", "EV")],
                        default="ice",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "car", "verbose_name_plural": "cars", "db_table": "cars"},
        ),
        migrations.CreateModel(
            name="CarMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("manager", "Manager"), ("viewer", "Viewer")],
                        default="viewer",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("pending", "Pending"), ("revoked", "Revoked")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="cars.car",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_car_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "car membership",
                "verbose_name_plural": "car memberships",
                "db_table": "car_memberships",
            },
        ),
        migrations.AddIndex(model_name="car", index=models.Index(fields=["normalized_plate_number"], name="cars_normali_f4656e_idx")),
        migrations.AddIndex(model_name="car", index=models.Index(fields=["powertrain_type"], name="cars_powertr_353cf9_idx")),
        migrations.AddIndex(model_name="carmembership", index=models.Index(fields=["status"], name="car_membersh_status_28e15b_idx")),
        migrations.AddIndex(model_name="carmembership", index=models.Index(fields=["role"], name="car_membersh_role_5bb6de_idx")),
        migrations.AddConstraint(
            model_name="carmembership",
            constraint=models.UniqueConstraint(fields=("car", "user"), name="uq_car_membership_car_user"),
        ),
    ]
