# Generated by Codex on 2026-04-29

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("telegram", "0002_botconversationstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantInteraction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("chat_id", models.BigIntegerField()),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True)),
                ("provider", models.CharField(max_length=64)),
                ("model_name", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[("succeeded", "Succeeded"), ("failed", "Failed")],
                        default="succeeded",
                        max_length=16,
                    ),
                ),
                ("car_context", models.JSONField(blank=True, default=dict)),
                ("response_metadata", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "telegram_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_interactions",
                        to="telegram.telegramaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "assistant interaction",
                "verbose_name_plural": "assistant interactions",
                "db_table": "assistant_interactions",
            },
        ),
        migrations.AddIndex(
            model_name="assistantinteraction",
            index=models.Index(fields=["chat_id", "created_at"], name="assistant_chat_created_idx"),
        ),
        migrations.AddIndex(
            model_name="assistantinteraction",
            index=models.Index(fields=["user", "created_at"], name="assistant_user_created_idx"),
        ),
        migrations.AddIndex(
            model_name="assistantinteraction",
            index=models.Index(fields=["status"], name="assistant_status_idx"),
        ),
    ]
