# Generated by Django 5.2.13 on 2026-04-14 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OdometerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("value", models.PositiveBigIntegerField()),
                ("entry_date", models.DateField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("maintenance_record", "Maintenance Record"),
                            ("ocr", "OCR"),
                            ("system", "System"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odometer_entries",
                        to="cars.car",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_odometer_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "odometer entry",
                "verbose_name_plural": "odometer entries",
                "db_table": "odometer_entries",
            },
        ),
        migrations.AddIndex(
            model_name="odometerentry",
            index=models.Index(fields=["car", "entry_date"], name="odometer_en_car_id_4cd278_idx"),
        ),
        migrations.AddIndex(
            model_name="odometerentry",
            index=models.Index(fields=["source"], name="odometer_en_source_72a52a_idx"),
        ),
    ]
