# Generated by Django 5.2.13 on 2026-04-14 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_user_id", models.BigIntegerField(unique=True)),
                ("chat_id", models.BigIntegerField()),
                ("username", models.CharField(blank=True, max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255)),
                ("language_code", models.CharField(blank=True, max_length=16)),
                ("is_blocked", models.BooleanField(default=False)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "telegram account",
                "verbose_name_plural": "telegram accounts",
                "db_table": "telegram_accounts",
            },
        ),
        migrations.AddIndex(
            model_name="telegramaccount",
            index=models.Index(fields=["user"], name="telegram_ac_user_id_4a1f42_idx"),
        ),
        migrations.AddIndex(
            model_name="telegramaccount",
            index=models.Index(fields=["chat_id"], name="telegram_ac_chat_id_83994e_idx"),
        ),
        migrations.AddIndex(
            model_name="telegramaccount",
            index=models.Index(fields=["is_blocked"], name="telegram_ac_is_bloc_176130_idx"),
        ),
    ]
