# Generated by Django 5.2.13 on 2026-04-14 00:00

import django.db.models.deletion
import apps.telegram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotConversationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("chat_id", models.BigIntegerField()),
                ("flow_name", models.CharField(max_length=64)),
                ("state_name", models.CharField(max_length=64)),
                ("state_payload", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField(default=apps.telegram.models.default_conversation_expiry)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "telegram_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversation_states",
                        to="telegram.telegramaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "bot conversation state",
                "verbose_name_plural": "bot conversation states",
                "db_table": "bot_conversation_states",
            },
        ),
        migrations.AddConstraint(
            model_name="botconversationstate",
            constraint=models.UniqueConstraint(fields=("chat_id", "flow_name"), name="uq_bot_state_chat_flow"),
        ),
        migrations.AddIndex(
            model_name="botconversationstate",
            index=models.Index(fields=["chat_id", "flow_name"], name="bot_convers_chat_id_d2f0ee_idx"),
        ),
        migrations.AddIndex(
            model_name="botconversationstate",
            index=models.Index(fields=["expires_at"], name="bot_convers_expires_82b4db_idx"),
        ),
    ]
