# Generated by Django 5.2.13 on 2026-04-29 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0002_botconversationstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedTelegramUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("update_id", models.BigIntegerField(unique=True)),
                ("chat_id", models.BigIntegerField(blank=True, null=True)),
                ("telegram_user_id", models.BigIntegerField(blank=True, null=True)),
                ("update_type", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("processing", "Processing"), ("processed", "Processed")],
                        default="processed",
                        max_length=16,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "processed Telegram update",
                "verbose_name_plural": "processed Telegram updates",
                "db_table": "processed_telegram_updates",
            },
        ),
        migrations.AddIndex(
            model_name="processedtelegramupdate",
            index=models.Index(fields=["status"], name="proc_tg_status_63af2f_idx"),
        ),
        migrations.AddIndex(
            model_name="processedtelegramupdate",
            index=models.Index(fields=["processed_at"], name="proc_tg_processed_b0f18c_idx"),
        ),
        migrations.AddIndex(
            model_name="processedtelegramupdate",
            index=models.Index(fields=["chat_id"], name="processed_t_chat_id_a5f6db_idx"),
        ),
    ]
