# Generated by Django 5.2.13 on 2026-04-14 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_date", models.DateField()),
                ("odometer", models.PositiveBigIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(choices=[("draft", "Draft"), ("final", "Final")], default="draft", max_length=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="cars.car",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_maintenance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paid_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paid_maintenance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "maintenance record",
                "verbose_name_plural": "maintenance records",
                "db_table": "maintenance_records",
            },
        ),
        migrations.CreateModel(
            name="MaintenanceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("part", "Part"),
                            ("labor", "Labor"),
                            ("service", "Service"),
                            ("fee", "Fee"),
                            ("fluid", "Fluid"),
                            ("filter", "Filter"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("paid_by_label", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "maintenance_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="maintenance.maintenancerecord",
                    ),
                ),
                (
                    "paid_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paid_maintenance_line_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "maintenance line item",
                "verbose_name_plural": "maintenance line items",
                "db_table": "maintenance_line_items",
            },
        ),
        migrations.AddIndex(
            model_name="maintenancerecord",
            index=models.Index(fields=["car", "event_date"], name="maintenanc_car_id_ffd987_idx"),
        ),
        migrations.AddIndex(
            model_name="maintenancerecord",
            index=models.Index(fields=["status"], name="maintenanc_status_206c4b_idx"),
        ),
        migrations.AddIndex(
            model_name="maintenancelineitem",
            index=models.Index(fields=["item_type"], name="maintenanc_item_ty_16945b_idx"),
        ),
    ]
